import React,{useEffect,useState} from 'react';
import {Modal,ScrollView,Text,View} from 'react-native';
import {api} from '../services/api';
import {LocationDraft,Province} from '../types';
import {Button,ErrorText,Field,errorMessage,styles} from './ui';
import MapPicker from './MapPicker';
export const emptyLocation=():LocationDraft=>({contact_name:'',phone:'',province_code:'',ward:'',village:'',detail:'',latitude:null,longitude:null});
export function validateLocation(v:LocationDraft){if(!v.contact_name.trim()||!v.phone.trim()||!v.province_code||!v.ward.trim()||!v.detail.trim())throw new Error('Điền đủ tên, số điện thoại, tỉnh/thành, xã/phường và địa chỉ chi tiết.');if(v.latitude===null||v.longitude===null)throw new Error('Hãy chọn vị trí trên OpenStreetMap.');return {...v,latitude:v.latitude,longitude:v.longitude};}
export default function LocationForm({value,onChange,recipient=false}:{value:LocationDraft;onChange:(v:LocationDraft)=>void;recipient?:boolean}){
 const [provinces,setProvinces]=useState<Province[]>([]),[pickProvince,setPickProvince]=useState(false),[search,setSearch]=useState(''),[map,setMap]=useState(false),[error,setError]=useState(''),[configured,setConfigured]=useState(true);
 async function load(){try{const c=await api<{provinces:Province[];configured:boolean}>('/maps/config');setProvinces(c.provinces);setConfigured(c.configured);setError('');}catch(e){setError(errorMessage(e));}}
 useEffect(()=>{void load();},[]);
 function set<K extends keyof LocationDraft>(key:K,v:LocationDraft[K]){onChange({...value,[key]:v});}
 return <View style={{gap:13}}><Field label={recipient?'Họ tên người nhận':'Họ tên người gửi'} value={value.contact_name} onChangeText={v=>set('contact_name',v)} maxLength={120}/><Field label={recipient?'Số điện thoại người nhận':'Số điện thoại người gửi'} value={value.phone} onChangeText={v=>set('phone',v)} keyboardType="phone-pad" maxLength={20}/><Text style={styles.label}>Tỉnh / Thành phố</Text><Button title={provinces.find(p=>p.code===value.province_code)?.name||'Chọn tỉnh / thành phố'} variant="secondary" onPress={()=>setPickProvince(true)}/><Field label="Xã / Phường" value={value.ward} onChangeText={v=>set('ward',v)} maxLength={120}/><Field label="Thôn / Xóm (nếu có)" value={value.village} onChangeText={v=>set('village',v)} maxLength={120}/><Field label="Địa chỉ chi tiết" value={value.detail} onChangeText={v=>set('detail',v)} maxLength={255}/><Button title={value.latitude===null?'Chọn vị trí trên OpenStreetMap':'Đổi vị trí trên OpenStreetMap'} variant="secondary" onPress={()=>setMap(true)}/>{value.latitude!==null&&<Text style={styles.muted}>Vị trí: {value.latitude.toFixed(6)}, {value.longitude?.toFixed(6)}</Text>}{!configured&&<Text style={styles.error}>Dịch vụ bản đồ chưa sẵn sàng. Vui lòng thử lại.</Text>}<ErrorText message={error}/>{!!error&&<Button title="Tải lại danh sách tỉnh" onPress={()=>void load()}/>}
 {map&&<MapPicker initial={value.latitude!==null&&value.longitude!==null?{latitude:value.latitude,longitude:value.longitude}:undefined} onClose={()=>setMap(false)} onSelect={p=>onChange({...value,latitude:p.latitude,longitude:p.longitude,province_code:p.province_code||value.province_code})}/>}
 <Modal visible={pickProvince} animationType="slide" onRequestClose={()=>setPickProvince(false)}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Button title="Đóng danh sách tỉnh" variant="secondary" onPress={()=>setPickProvince(false)}/><Field label="Tìm tỉnh / thành phố" value={search} onChangeText={setSearch}/>{provinces.filter(p=>p.name.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))).map(p=><Button key={p.code} title={p.name} variant="secondary" onPress={()=>{set('province_code',p.code);setPickProvince(false);}}/>)}</ScrollView></Modal></View>;
}
