import React from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View, ViewStyle } from 'react-native';
import { Status } from '../types';

export const colors={green:'#155d4b',mint:'#e8f3ed',ink:'#263d35',muted:'#7c8d85',bg:'#f5f7f6',line:'#e3eae6',red:'#b45b50'};
export const statusLabels:Record<Status,string>={pending:'Chờ nhận',accepted:'Đã nhận',awaiting_pickup:'Chờ lấy hàng',picked_up:'Đã lấy hàng',delivering:'Đang giao',completed:'Hoàn thành',incomplete:'Chưa hoàn thành',cancelled:'Đã hủy'};
export const routeLabels={same_province:'Nội tỉnh',same_region:'Nội miền',inter_region:'Liên miền'};
export const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n||0));
export const date=(value:string)=>new Date(value).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
export const errorMessage=(e:unknown)=>e instanceof Error?e.message:'Đã xảy ra lỗi. Vui lòng thử lại.';
export function Button({title,onPress,busy=false,variant='primary',disabled=false}:{title:string;onPress:()=>void;busy?:boolean;variant?:'primary'|'secondary'|'danger';disabled?:boolean}) {return <Pressable accessibilityRole="button" accessibilityState={{disabled:busy||disabled}} onPress={onPress} disabled={busy||disabled} style={({pressed})=>[styles.button,variant==='secondary'&&styles.secondary,variant==='danger'&&styles.danger,(busy||disabled)&&{opacity:.5},pressed&&{opacity:.8}]}>{busy?<ActivityIndicator color={variant==='primary'?'white':colors.green}/>:<Text style={[styles.buttonText,variant==='secondary'&&{color:colors.green},variant==='danger'&&{color:colors.red}]}>{title}</Text>}</Pressable>;}
export function Field({label,...props}:TextInputProps&{label:string}) {return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor="#a1aea7" {...props} style={[styles.input,props.multiline&&{minHeight:84,textAlignVertical:'top'},props.style]}/></View>;}
export function ErrorText({message}:{message:string}) {return message?<Text accessibilityRole="alert" style={styles.error}>{message}</Text>:null;}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}) {return <View style={[styles.card,style]}>{children}</View>;}
export function Badge({status}:{status:Status}) {const error=['incomplete','cancelled'].includes(status);const pending=['pending','accepted','awaiting_pickup'].includes(status);return <View style={[styles.badge,{backgroundColor:error?'#fcefee':pending?'#fff4e1':colors.mint}]}><Text style={{fontSize:11,fontWeight:'600',color:error?colors.red:pending?'#aa8139':colors.green}}>{statusLabels[status]}</Text></View>;}
export function Chips<T extends string>({items,value,onChange}:{items:{value:T;label:string}[];value:T;onChange:(value:T)=>void}) {return <View style={styles.chips}>{items.map(item=><Pressable key={item.value} accessibilityRole="button" accessibilityState={{selected:value===item.value}} onPress={()=>onChange(item.value)} style={[styles.chip,value===item.value&&styles.chipActive]}><Text style={[styles.chipText,value===item.value&&{color:'white'}]}>{item.label}</Text></Pressable>)}</View>;}
export function Empty({title,detail}:{title:string;detail:string}) {return <View style={{padding:35,alignItems:'center',gap:12}}><Text style={{fontSize:35,color:colors.green}}>◇</Text><Text style={styles.subtitle}>{title}</Text><Text style={[styles.muted,{textAlign:'center',lineHeight:22}]}>{detail}</Text></View>;}
export const styles=StyleSheet.create({
 screen:{flex:1,backgroundColor:colors.bg},content:{padding:22,paddingBottom:35,gap:16},title:{fontSize:27,fontWeight:'700',color:colors.ink,letterSpacing:-.6},subtitle:{fontSize:17,fontWeight:'600',color:colors.ink},muted:{fontSize:12,color:colors.muted,lineHeight:19},eyebrow:{fontSize:10,letterSpacing:1.8,fontWeight:'700',color:colors.green},card:{padding:19,borderRadius:15,borderWidth:1,borderColor:colors.line,backgroundColor:'white',gap:13},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},button:{backgroundColor:colors.green,padding:15,minHeight:48,borderRadius:9,alignItems:'center',justifyContent:'center'},secondary:{backgroundColor:colors.mint},danger:{backgroundColor:'#fcefee'},buttonText:{fontSize:13,fontWeight:'600',color:'white'},field:{gap:8},label:{fontSize:12,fontWeight:'600',color:'#536a5e'},input:{backgroundColor:'white',borderWidth:1,borderColor:colors.line,borderRadius:8,padding:13,minHeight:46,fontSize:14,color:colors.ink},error:{fontSize:12,color:colors.red,lineHeight:20,paddingVertical:6},badge:{alignSelf:'flex-start',borderRadius:5,paddingHorizontal:9,paddingVertical:6},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:colors.line,backgroundColor:'white',paddingHorizontal:13,paddingVertical:10,borderRadius:8},chipActive:{backgroundColor:colors.green,borderColor:colors.green},chipText:{fontSize:12,color:'#708277'},divider:{height:1,backgroundColor:colors.line},sectionTitle:{fontSize:12,fontWeight:'700',color:colors.green,marginTop:10},link:{fontSize:13,fontWeight:'600',color:colors.green},success:{fontSize:12,lineHeight:20,color:colors.green,backgroundColor:colors.mint,padding:12,borderRadius:8}
});
