import React,{useEffect,useState} from 'react';
import {ScrollView,Switch,Text,View} from 'react-native';
import {useAuth} from '../context/AuthContext';
import {api} from '../services/api';
import {Address,LocationDraft} from '../types';
import {Button,Card,ErrorText,Field,errorMessage,styles} from '../components/ui';
import LocationForm,{emptyLocation,validateLocation} from '../components/LocationForm';
export default function AddressesScreen({onBack}:{onBack:()=>void}){
 const {user}=useAuth();const [items,setItems]=useState<Address[]>([]),[editing,setEditing]=useState<number|null>(null),[form,setForm]=useState<LocationDraft>(emptyLocation),[label,setLabel]=useState('Nhà riêng'),[isDefault,setDefault]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState<number|null>(null);
 async function load(){try{setItems((await api<{items:Address[]}>('/addresses')).items);setError('');}catch(e){setError(errorMessage(e));}}
 useEffect(()=>{void load();},[]);
 function edit(a?:Address){setEditing(a?.id||0);setLabel(a?.label||'Nhà riêng');setDefault(!!a?.is_default);setForm(a?{contact_name:a.contact_name,phone:a.phone,province_code:a.province_code,ward:a.ward,village:a.village,detail:a.detail,latitude:Number(a.latitude),longitude:Number(a.longitude)}:{...emptyLocation(),contact_name:user?.name||'',phone:user?.phone||''});setError('');}
 async function save(){if(busy)return;setBusy(true);setError('');try{const body={...validateLocation(form),label,is_default:isDefault};await api('/addresses'+(editing?'/'+editing:''),editing?'PATCH':'POST',body);setEditing(null);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function remove(){if(!deleting||busy)return;setBusy(true);try{await api('/addresses/'+deleting,'DELETE');setDeleting(null);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <ScrollView style={styles.screen} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Button title="← Quay lại" variant="secondary" onPress={onBack}/><Text style={styles.title}>Địa chỉ của bạn</Text><ErrorText message={error}/>{editing!==null?<Card><Field label="Tên địa chỉ" value={label} onChangeText={setLabel} maxLength={80}/><LocationForm value={form} onChange={setForm}/><View style={styles.row}><Text style={styles.label}>Địa chỉ mặc định</Text><Switch accessibilityLabel="Địa chỉ mặc định" value={isDefault} onValueChange={setDefault}/></View><Button title="Lưu địa chỉ" onPress={()=>void save()} busy={busy}/><Button title="Hủy chỉnh sửa" onPress={()=>setEditing(null)} variant="secondary" disabled={busy}/></Card>:<><Button title="+ Thêm địa chỉ mới" onPress={()=>edit()}/>{!items.length&&<Text style={styles.muted}>Lưu một địa chỉ có vị trí bản đồ để sử dụng làm điểm lấy hàng.</Text>}{items.map(a=><Card key={a.id}><Text style={styles.subtitle}>{a.label}{a.is_default?' · Mặc định':''}</Text><Text style={styles.muted}>{a.contact_name} · {a.phone}</Text><Text style={styles.muted}>{a.formatted_address}</Text><Button title="Sửa địa chỉ" onPress={()=>edit(a)} variant="secondary"/><Button title="Xóa địa chỉ" onPress={()=>setDeleting(a.id)} variant="danger"/>{deleting===a.id&&<><Text style={styles.muted}>Xóa địa chỉ này khỏi sổ địa chỉ?</Text><Button title="Xác nhận xóa địa chỉ" onPress={()=>void remove()} busy={busy} variant="danger"/><Button title="Giữ địa chỉ" onPress={()=>setDeleting(null)} variant="secondary"/></>}</Card>)}</>}</ScrollView>;
}
