import React,{useState} from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, Text, View } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { Button, Card, ErrorText, Field, colors, errorMessage, styles } from '../components/ui';

export default function AuthScreen(){
  const auth=useAuth();const [register,setRegister]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [form,setForm]=useState({name:'',email:'',password:'',phone:'',address:''});
  const update=(key:keyof typeof form)=>(value:string)=>setForm(prev=>({...prev,[key]:value}));
  async function submit(){if(busy)return;setBusy(true);setError('');try{if(register)await auth.register(form);else await auth.login(form.email,form.password);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[styles.content,{paddingTop:45}]}><View style={{gap:14,paddingBottom:18}}><View style={{backgroundColor:colors.green,width:55,height:55,borderRadius:16,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#e5efb7',fontSize:18,fontWeight:'800'}}>CPN</Text></View><Text style={styles.eyebrow}>CHUYỂN PHÁT NHANH</Text><Text style={[styles.title,{fontSize:31}]}>Gửi niềm tin.{`\n`}Nhận an tâm.</Text><Text style={styles.muted}>Kết nối mọi hành trình, ngay trong tay bạn.</Text></View><Card><Text style={styles.subtitle}>{register?'Tạo tài khoản khách hàng':'Chào mừng trở lại'}</Text><Text style={styles.muted}>{register?'Bắt đầu gửi kiện hàng đầu tiên của bạn.':'Dành cho khách hàng và nhân viên vận chuyển.'}</Text>{register&&<Field label="Họ và tên" value={form.name} onChangeText={update('name')} maxLength={120}/>}<Field label="Email" value={form.email} onChangeText={update('email')} keyboardType="email-address" autoCapitalize="none" autoComplete="email" maxLength={190}/><Field label="Mật khẩu" value={form.password} onChangeText={update('password')} secureTextEntry autoComplete={register?'new-password':'current-password'}/>{register&&<><Field label="Số điện thoại" value={form.phone} onChangeText={update('phone')} keyboardType="phone-pad" maxLength={20}/><Field label="Địa chỉ lấy hàng mặc định" value={form.address} onChangeText={update('address')} multiline maxLength={500}/></>}<ErrorText message={error}/><Button title={register?'Đăng ký':'Đăng nhập'} busy={busy} onPress={()=>void submit()}/><Button title={register?'Đã có tài khoản? Đăng nhập':'Chưa có tài khoản? Đăng ký'} variant="secondary" disabled={busy} onPress={()=>{setRegister(!register);setError('');}}/></Card><Text style={[styles.muted,{textAlign:'center',fontSize:10}]}>CPN · Kết nối niềm tin, chuyển trọn giá trị</Text></ScrollView></KeyboardAvoidingView>;
}
