import React,{useEffect,useState} from 'react';
import { KeyboardAvoidingView,Platform,ScrollView,Text,View } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import { Order,Service } from '../types';
import { Button,Card,Chips,ErrorText,Field,errorMessage,money,styles } from '../components/ui';

export default function CreateOrderScreen({onCreated}:{onCreated:(id:number)=>void}){
  const {user}=useAuth();const [services,setServices]=useState<Service[]>([]);const [serviceId,setServiceId]=useState('');const [zone,setZone]=useState<'same_city'|'domestic'>('same_city');const [payer,setPayer]=useState<'sender'|'receiver'>('sender');const [fee,setFee]=useState<number|null>(null);const [quoteError,setQuoteError]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [form,setForm]=useState({sender_name:user?.name||'',sender_phone:user?.phone||'',sender_address:user?.address||'',receiver_name:'',receiver_phone:'',receiver_address:'',package_name:'',weight:'1',cod_amount:'0',note:''});
  const update=(key:keyof typeof form)=>(value:string)=>setForm(prev=>({...prev,[key]:value}));
  const load=async()=>{try{setError('');const data=await api<{items:Service[]}>('/services');setServices(data.items);setServiceId(String(data.items[0]?.id||''));}catch(e){setError(errorMessage(e));}};
  useEffect(()=>{void load();},[]);
  useEffect(()=>{let active=true;setFee(null);setQuoteError('');if(!serviceId)return;const timer=setTimeout(()=>{api<{shipping_fee:number}>('/services/quote','POST',{service_id:Number(serviceId),weight:Number(form.weight.replace(',','.')),zone}).then(data=>{if(active)setFee(data.shipping_fee);}).catch(e=>{if(active)setQuoteError(errorMessage(e));});},350);return()=>{active=false;clearTimeout(timer);};},[serviceId,form.weight,zone]);
  async function submit(){if(busy)return;setBusy(true);setError('');try{const data=await api<{order:Order}>('/orders','POST',{...form,service_id:Number(serviceId),weight:Number(form.weight.replace(',','.')),cod_amount:Number(form.cod_amount),zone,payer});onCreated(data.order.id);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={{gap:7}}><Text style={styles.eyebrow}>MỘT HÀNH TRÌNH MỚI</Text><Text style={styles.title}>Tạo đơn hàng</Text><Text style={styles.muted}>Điền thông tin, chúng tôi sẽ đến lấy hàng.</Text></View><Card><Text style={styles.sectionTitle}>01 · Người gửi</Text><Field label="Họ tên người gửi" value={form.sender_name} onChangeText={update('sender_name')} maxLength={120}/><Field label="Số điện thoại người gửi" value={form.sender_phone} onChangeText={update('sender_phone')} keyboardType="phone-pad" maxLength={20}/><Field label="Địa chỉ lấy hàng" value={form.sender_address} onChangeText={update('sender_address')} multiline maxLength={500}/></Card><Card><Text style={styles.sectionTitle}>02 · Người nhận</Text><Field label="Họ tên người nhận" value={form.receiver_name} onChangeText={update('receiver_name')} maxLength={120}/><Field label="Số điện thoại người nhận" value={form.receiver_phone} onChangeText={update('receiver_phone')} keyboardType="phone-pad" maxLength={20}/><Field label="Địa chỉ giao hàng" value={form.receiver_address} onChangeText={update('receiver_address')} multiline maxLength={500}/></Card><Card><Text style={styles.sectionTitle}>03 · Kiện hàng & dịch vụ</Text><Field label="Tên hàng hóa" value={form.package_name} onChangeText={update('package_name')} maxLength={200}/><Field label="Khối lượng (kg)" value={form.weight} onChangeText={update('weight')} keyboardType="decimal-pad"/><Text style={styles.label}>Dịch vụ</Text><Chips items={services.map(s=>({value:String(s.id),label:`${s.name} · ${s.estimated_days}`}))} value={serviceId} onChange={setServiceId}/>{!services.length&&<Button title="Tải lại dịch vụ" variant="secondary" onPress={()=>void load()}/>}<Text style={styles.label}>Tuyến vận chuyển</Text><Chips items={[{value:'same_city',label:'Nội tỉnh'},{value:'domestic',label:'Liên tỉnh'}]} value={zone} onChange={setZone}/><Field label="Tiền thu hộ COD (đ)" value={form.cod_amount} onChangeText={update('cod_amount')} keyboardType="numeric"/><Text style={styles.label}>Người trả cước</Text><Chips items={[{value:'sender',label:'Người gửi'},{value:'receiver',label:'Người nhận'}]} value={payer} onChange={setPayer}/><Field label="Ghi chú giao hàng" value={form.note} onChangeText={update('note')} multiline maxLength={1000}/></Card><Card><View style={styles.row}><Text style={styles.label}>Cước vận chuyển</Text><Text style={styles.subtitle}>{fee===null?'…':money(fee)}</Text></View><Text style={styles.muted}>Giá cho 1 kg đầu + mỗi 0,5 kg vượt mức + phụ phí liên tỉnh (nếu có). COD không tính vào cước.</Text><ErrorText message={quoteError}/><ErrorText message={error}/><Button title="Xác nhận tạo đơn" busy={busy} disabled={fee===null} onPress={()=>void submit()}/></Card></ScrollView></KeyboardAvoidingView>;
}
