import React,{useEffect,useState} from 'react';
import {AppState,Pressable,RefreshControl,ScrollView,Text,View} from 'react-native';
import {api} from '../services/api';
import {Notice,Page} from '../types';
import {Button,Card,Empty,ErrorText,date,errorMessage,styles} from '../components/ui';
export default function NotificationsScreen({onOpen}:{onOpen:(id:number)=>void}){
 const [data,setData]=useState<Page<Notice>&{unread_count:number}>({items:[],total:0,page:1,limit:15,unread_count:0}),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;async function refresh(){try{const r=await api<Page<Notice>&{unread_count:number}>('/notifications?page='+page+'&limit=15');if(live){setData(r);setError('');}}catch(e){if(live)setError(errorMessage(e));}}void refresh();const timer=setInterval(()=>{if(AppState.currentState==='active'||AppState.currentState===null)void refresh();},15000);return()=>{live=false;clearInterval(timer);};},[page]);
 async function load(){setBusy(true);try{setData(await api('/notifications?page='+page+'&limit=15'));setError('');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function open(n:Notice){try{await api('/notifications/'+n.id+'/read','PATCH');if(n.order_id)onOpen(n.order_id);else await load();}catch(e){setError(errorMessage(e));}}
 async function readAll(){try{await api('/notifications/read-all','PATCH');await load();}catch(e){setError(errorMessage(e));}}
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()}/>}><Text style={styles.title}>Thông báo</Text><Text style={styles.muted}>{data.unread_count} thông báo chưa đọc · Cập nhật mỗi 15 giây khi mở trang.</Text><Button title="Đánh dấu tất cả đã đọc" variant="secondary" onPress={()=>void readAll()}/><ErrorText message={error}/>{!data.items.length&&<Empty title="Chưa có thông báo" detail="Cập nhật trạng thái và lời mời đánh giá sẽ xuất hiện tại đây."/>}{data.items.map(n=><Pressable key={n.id} accessibilityRole="button" accessibilityLabel={n.title} onPress={()=>void open(n)}><Card style={!n.read_at?{borderColor:'#155d4b'}:{}}><Text style={styles.subtitle}>{n.title}</Text><Text style={styles.muted}>{n.message}</Text><Text style={styles.muted}>{date(n.created_at)}{n.read_at?' · Đã đọc':' · Chưa đọc'}</Text>{n.type==='review_invite'&&<Text style={styles.link}>Mở đơn và đánh giá nhân viên →</Text>}</Card></Pressable>)}<View style={styles.row}><Button title="← Trước" variant="secondary" disabled={page<=1} onPress={()=>setPage(page-1)}/><Text style={styles.muted}>Trang {page}</Text><Button title="Sau →" variant="secondary" disabled={page*15>=data.total} onPress={()=>setPage(page+1)}/></View></ScrollView>;
}
