import React,{useCallback,useEffect,useState} from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, Text, View } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import { Order,Page,Status } from '../types';
import { Badge,Button,Card,Chips,Empty,ErrorText,Field,colors,date,errorMessage,money,styles,statusLabels } from '../components/ui';

export default function OrdersScreen({onOpen,onCreate,scope}:{onOpen:(id:number)=>void;onCreate:()=>void;scope:'mine'|'waiting'}){
  const {user}=useAuth();const employee=user?.role==='employee';const [data,setData]=useState<Page<Order>>({items:[],total:0,page:1,limit:10});const [page,setPage]=useState(1);const [filter,setFilter]=useState('');const [q,setQ]=useState('');const [search,setSearch]=useState('');const [busy,setBusy]=useState(true);const [error,setError]=useState('');
  const load=useCallback(async()=>{setBusy(true);setError('');try{setData(await api(`/orders?scope=${scope}&page=${page}&limit=10&q=${encodeURIComponent(search)}${filter?'&status='+filter:''}`));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}},[page,filter,search,scope]);
  useEffect(()=>{void load();},[load]);
  const filters=[{value:'',label:'Tất cả'},...(employee?['accepted','awaiting_pickup','picked_up','delivering','incomplete','completed']:['pending','accepted','awaiting_pickup','delivering','completed','incomplete','cancelled']).map(s=>({value:s,label:statusLabels[s as Status]}))];
  return <ScrollView style={styles.screen} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()} tintColor={colors.green}/>}><View style={{gap:7}}><Text style={styles.eyebrow}>{employee?'SẴN SÀNG CHO HÀNH TRÌNH MỚI':'MỖI KIỆN HÀNG LÀ MỘT KẾT NỐI'}</Text><Text style={styles.title}>{employee?(scope==='waiting'?'Đơn đang chờ':'Đơn đã nhận'):'Lịch sử đơn hàng'}</Text><Text style={styles.muted}>Xin chào, {user?.name} · {data.total} đơn theo bộ lọc</Text></View>{!employee&&<Button title="+ Tạo đơn hàng mới" onPress={onCreate}/>}<View style={{gap:10}}><Field label="Tìm đơn hàng" placeholder="Mã vận đơn, người nhận, điện thoại" value={q} onChangeText={setQ} returnKeyType="search" onSubmitEditing={()=>{setPage(1);setSearch(q.trim());}}/><Button title="Tìm kiếm" variant="secondary" onPress={()=>{setPage(1);setSearch(q.trim());}}/></View>{scope!=='waiting'&&<Chips items={filters} value={filter} onChange={v=>{setFilter(v);setPage(1);}}/>}<ErrorText message={error}/>{error?<Button title="Thử tải lại" variant="secondary" onPress={()=>void load()}/>:busy?<ActivityIndicator color={colors.green} style={{padding:30}}/>:data.items.length===0?<Empty title="Chưa có đơn hàng" detail={employee?'Đơn khách hàng ủy thác xuất hiện ở Đơn đang chờ. Nhấn vào thẻ để xem và nhận vận chuyển.':'Tạo một đơn hàng mới hoặc thay đổi bộ lọc tìm kiếm.'}/>:data.items.map(o=><Pressable key={o.id} onPress={()=>onOpen(o.id)} accessibilityRole="button" accessibilityLabel={`Xem đơn ${o.tracking_code}`}><Card><View style={styles.row}><Text style={[styles.link,{fontSize:12}]}>{o.tracking_code}</Text><Text style={[styles.muted,{fontSize:10}]}>{date(o.created_at)}</Text></View><Badge status={o.status}/><Text style={{fontSize:16,fontWeight:'600',color:colors.ink}}>{o.receiver_name}</Text><Text style={styles.muted}>{o.receiver_address}</Text><View style={styles.divider}/><View style={styles.row}><Text style={styles.muted}>{o.service_name} · {o.weight} kg</Text><Text style={styles.link}>{money(o.total_amount ?? o.shipping_fee)}</Text></View><View style={styles.row}><Text style={styles.muted}>Thu hộ COD: {money(o.cod_amount)}</Text><Text style={styles.link}>Chi tiết →</Text></View></Card></Pressable>)}<View style={styles.row}><Button title="← Trước" disabled={page===1||busy} variant="secondary" onPress={()=>setPage(p=>p-1)}/><Text style={styles.muted}>{page} / {Math.max(1,Math.ceil(data.total/10))}</Text><Button title="Sau →" disabled={page*10>=data.total||busy} variant="secondary" onPress={()=>setPage(p=>p+1)}/></View></ScrollView>;
}
