import React,{useEffect,useState} from 'react';
import {KeyboardAvoidingView,Platform,ScrollView,Text,View} from 'react-native';
import {useAuth} from '../context/AuthContext';
import {api} from '../services/api';
import {EmployeeSummary,User} from '../types';
import {Button,Card,ErrorText,Field,date,errorMessage,styles} from '../components/ui';
import AddressesScreen from './AddressesScreen';
export default function ProfileScreen(){
 const {user,updateUser,logout}=useAuth(),employee=user?.role==='employee';
 const [form,setForm]=useState({name:user?.name||'',phone:user?.phone||'',address:user?.address||''}),[password,setPassword]=useState({current_password:'',new_password:''}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[addresses,setAddresses]=useState(false),[summary,setSummary]=useState<EmployeeSummary|null>(null),[page,setPage]=useState(1);
 async function load(){try{setSummary(await api('/employees/me?page='+page+'&limit=10'));}catch(e){setError(errorMessage(e));}}
 useEffect(()=>{if(employee)void load();},[employee,page]);
 async function act(kind:string){if(busy)return;setBusy(kind);setError('');setSuccess('');try{if(kind==='save'){const result=await api<{user:User}>('/auth/me','PATCH',form);updateUser(result.user);setSuccess('Đã lưu thông tin tài khoản.');}else if(kind==='password'){await api('/auth/change-password','POST',password);await logout();}else await logout();}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 if(addresses)return <AddressesScreen onBack={()=>setAddresses(false)}/>;
 const p=summary?.profile;
 return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Text style={styles.eyebrow}>KHÔNG GIAN CỦA BẠN</Text><Text style={styles.title}>Cá nhân</Text><Text style={styles.muted}>{user?.email} · {employee?'Nhân viên vận chuyển':'Khách hàng'}</Text><ErrorText message={error}/>{!!success&&<Text style={styles.success}>{success}</Text>}<Card><Text style={styles.subtitle}>Thông tin cá nhân</Text>{employee?<><Text style={styles.label}>{user?.name} · {user?.phone}</Text><Text style={styles.muted}>{user?.address||'Chưa có địa chỉ liên hệ'}</Text>{p?<><Text style={styles.muted}>Mã nhân viên: {p.employee_code}</Text><Text style={styles.muted}>CCCD: {p.identity_number||'Chưa bổ sung'}</Text><Text style={styles.muted}>Quê quán: {p.hometown||'Chưa bổ sung'}</Text><Text style={styles.muted}>Ngày vào làm: {date(p.hired_at)}</Text><Text style={styles.muted}>{p.employment_status==='active'?'Đang làm việc':'Đã ngừng làm việc'}</Text></>:<Text style={styles.muted}>Quản lí chưa bổ sung hồ sơ nhân viên.</Text>}</>:<><Field label="Họ và tên" value={form.name} onChangeText={name=>setForm({...form,name})} maxLength={120}/><Field label="Số điện thoại" value={form.phone} onChangeText={phone=>setForm({...form,phone})} keyboardType="phone-pad" maxLength={20}/><Field label="Địa chỉ liên hệ" value={form.address} onChangeText={address=>setForm({...form,address})} multiline maxLength={500}/><Button title="Lưu thông tin" busy={busy==='save'} disabled={!!busy} onPress={()=>void act('save')}/><Button title="Địa chỉ lấy hàng của tôi" variant="secondary" onPress={()=>setAddresses(true)}/></>}</Card>
 {employee&&<Card><Text style={styles.subtitle}>Thống kê vận chuyển</Text><Button title="Làm mới thống kê" variant="secondary" onPress={()=>void load()}/>{summary&&<><View style={styles.row}><Text style={styles.label}>Hoàn thành: {summary.stats.completed}</Text><Text style={styles.label}>Thất bại: {summary.stats.incomplete}</Text></View><Text style={styles.link}>★ {Number(summary.stats.average_stars).toFixed(2)}/5 · {summary.stats.review_count} đánh giá</Text>{summary.reviews.map(r=><View key={r.id} style={{gap:6,borderTopWidth:1,borderColor:'#e3eae6',paddingTop:12}}><Text style={styles.label}>{'★'.repeat(r.stars)} · {r.customer_name}</Text><Text style={styles.muted}>{r.comment}</Text><Text style={styles.muted}>{r.tracking_code} · {date(r.created_at)}</Text></View>)}<View style={styles.row}><Button title="Đánh giá trước" variant="secondary" disabled={page<=1} onPress={()=>setPage(page-1)}/><Button title="Đánh giá sau" variant="secondary" disabled={page*10>=summary.stats.review_count} onPress={()=>setPage(page+1)}/></View></>}</Card>}
 <Card><Text style={styles.subtitle}>Đổi mật khẩu</Text><Field label="Mật khẩu hiện tại" value={password.current_password} onChangeText={current_password=>setPassword({...password,current_password})} secureTextEntry autoComplete="current-password"/><Field label="Mật khẩu mới (ít nhất 8 ký tự)" value={password.new_password} onChangeText={new_password=>setPassword({...password,new_password})} secureTextEntry autoComplete="new-password"/><Button title="Đổi mật khẩu" variant="secondary" busy={busy==='password'} disabled={!!busy} onPress={()=>void act('password')}/><Text style={styles.muted}>Sau khi đổi mật khẩu, bạn cần đăng nhập lại trên các thiết bị.</Text></Card><Button title="Đăng xuất trên các thiết bị" variant="danger" busy={busy==='logout'} disabled={!!busy} onPress={()=>void act('logout')}/></ScrollView></KeyboardAvoidingView>;
}
