import React,{useState} from 'react';
import { KeyboardAvoidingView,Platform,ScrollView,Text } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import { User } from '../types';
import { Button,Card,ErrorText,Field,errorMessage,styles } from '../components/ui';

export default function ProfileScreen(){
  const {user,updateUser,logout}=useAuth();const [form,setForm]=useState({name:user?.name||'',phone:user?.phone||'',address:user?.address||''});const [password,setPassword]=useState({current_password:'',new_password:''});const [busy,setBusy]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');
  async function act(kind:string){if(busy)return;setBusy(kind);setError('');setSuccess('');try{if(kind==='save'){const result=await api<{user:User}>('/auth/me','PATCH',form);updateUser(result.user);setSuccess('Đã lưu thông tin tài khoản.');}else if(kind==='password'){await api('/auth/change-password','POST',password);await logout();}else await logout();}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Text style={styles.eyebrow}>KHÔNG GIAN CỦA BẠN</Text><Text style={styles.title}>Tài khoản</Text><Text style={styles.muted}>{user?.email} · {user?.role==='employee'?'Nhân viên vận chuyển':'Khách hàng'}</Text><ErrorText message={error}/>{!!success&&<Text style={styles.success}>{success}</Text>}<Card><Text style={styles.subtitle}>Thông tin cá nhân</Text><Field label="Họ và tên" value={form.name} onChangeText={name=>setForm({...form,name})} maxLength={120}/><Field label="Số điện thoại" value={form.phone} onChangeText={phone=>setForm({...form,phone})} keyboardType="phone-pad" maxLength={20}/><Field label="Địa chỉ mặc định" value={form.address} onChangeText={address=>setForm({...form,address})} multiline maxLength={500}/><Button title="Lưu thông tin" busy={busy==='save'} disabled={!!busy} onPress={()=>void act('save')}/></Card><Card><Text style={styles.subtitle}>Đổi mật khẩu</Text><Field label="Mật khẩu hiện tại" value={password.current_password} onChangeText={current_password=>setPassword({...password,current_password})} secureTextEntry autoComplete="current-password"/><Field label="Mật khẩu mới (ít nhất 8 ký tự)" value={password.new_password} onChangeText={new_password=>setPassword({...password,new_password})} secureTextEntry autoComplete="new-password"/><Button title="Đổi mật khẩu" variant="secondary" busy={busy==='password'} disabled={!!busy} onPress={()=>void act('password')}/><Text style={styles.muted}>Sau khi đổi mật khẩu, bạn cần đăng nhập lại trên các thiết bị.</Text></Card><Button title="Đăng xuất trên các thiết bị" variant="danger" busy={busy==='logout'} disabled={!!busy} onPress={()=>void act('logout')}/></ScrollView></KeyboardAvoidingView>;
}
